### ISSUE TITLE
swapped output file names

### ISSUE THREAD

**Issue by danrlu** [AndersenLab/trim-fq-nf#1]
in main.nf line 44: 

1_fastqc.zip 1_fastqc.zip 2_fastqc.html 2_fastqc.html 

should probably be 

1_fastqc.zip 2_fastqc.zip 1_fastqc.html 2_fastqc.html

thanks!

**Comment by danielecook** [comment]
I don't think this will be an issue once you swap in fastp; Close issue when resolved. Thanks!
