### ISSUE TITLE
How to sort by 2nd column for md5sum?

### ISSUE THREAD

**Issue by danrlu** [AndersenLab/trim-fq-nf#10]
Is there a way to sort the resulting md5.txt by file name (2nd column)? @danielecook 
`md5sum_pre.out.concat(md5sum_post.out).collectFile(name: md5sum_path, newLine:false)`

**Comment by danielecook** [comment]
See https://www.nextflow.io/docs/latest/operator.html#collectfile

I think ou can specify a `sort` option, but I am not sure it would work for the second column unless you used a closure.

Alternatively, you can collect the files in a separate process, and parse and sort it using bash.

**Comment by danrlu** [comment]
I fiddled around and the code got too messy XD So i'll settle for an easy work around. Thanks!!
