### ISSUE TITLE
Integrate conda environments for fastp and multiqc

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/trim-fq-nf#2]
All processes should specify a conda environment such as:

`conda "multiqc=(specific version)"`

**Comment by danrlu** [comment]
these conda env created by nextflow on the fly are (1) unnamed (2) in working directory that gets deleted once a month (3) cannot be easily called or re-used by other scripts.
 
![image](https://user-images.githubusercontent.com/20667188/75612311-dc687580-5ae7-11ea-8fd3-dfd3af558f46.png)

Unless there is a strong argument to do it this way, I will create a conda env for each pipeline and add them in the nextflow.config file. 

`process {
	conda = "/projects/b1059/software/conda_envs/trim-nf_env"
}`

**Comment by danielecook** [comment]
You can specify the Conda directory and prevent it from being deleted. See the next flow docs - it’s something like “cacheDir”.

https://www.nextflow.io/docs/latest/config.html?highlight=conda#scope-conda

I would make the location specific for quest. If working locally it doesn’t matter.

**Comment by danielecook** [comment]
Addressing 1 and 3:

You can use a yaml file to specify a Conda env and that can be named. Multiple pipelines can point to the same env file or if the Conda tools are identical the hash will be the same so they can be reused.

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually

A big reason to allow this flexibility is if you try to build an environment for the entire pipeline it will be difficult to build, and you will often find software dependency collisions.

I have tried to create an environment for the entire pipeline before and ran into issues doing so,  but feel free to experiment and if you can make it work then to go with what you think is best!

**Comment by danielecook** [comment]
You should think about unifying the quest configuration across all the pipelines too - I can help with that.

**Comment by danrlu** [comment]
I see what you're saying!! Very good points!

Now I think it's probably similar to either (a) have nextflow build and manage the conda env it uses, or (b) manually build conda env independent of nextflow and give the env path to nextflow. Let me sit on this for a bit while keep going forward with the pipeline. I'll come back to fix this one as needed.

**Comment by danielecook** [comment]
I wouldn’t worry about sharing environments between pipelines. As long as you define the cacheDir they ain’t have to be rebuilt and they are relatively lightweight. At the same time you can use env files to name them if you prefer. But again, do what you think is best.

**Comment by danielecook** [comment]
I had not realized I went both ways with the idea of a unified vs. separate quest environments....I don't have a strong preference.  There are pros/cons for each that are worth considering.

I think I lean slightly towards a unified quest configuration profile.

**Comment by danrlu** [comment]
Thanks for all the input Dan! It's really helpful to discuss all the options and the pros/cons for each. It's a very good learning process for me. 

I think our pipelines are not that complex, and can go either way as you said. So I will just do whatever is easier to implement, and easier for ppl in the lab to understand and to use. 

I will keep in mind all the pros/cons you pointed out! Thanks!
