### ISSUE TITLE
fix test data names

### ISSUE THREAD

**Issue by danrlu** [AndersenLab/trim-fq-nf#7]
from .fq.gz.fq.gz to .fq.gz

**Comment by danielecook** [comment]
One think you might consider is posting the commit hash for changes like this so it’s easier to track which specific commit addresses an issue. It’s not always necessary but can sometimes be helpful.

**Comment by danrlu** [comment]
Just like this? `b39f460`
will do for the future!

**Comment by danielecook** [comment]
Yep! Not necessary every time but for more important changes it is helpful. Thanks!
